pipeline:
  deploy-dry:
    image: archlinux
    commands:
      - pacman -Sy
      - pacman -S git python-pip python-setuptools zola --noconfirm
      - pip install bikeshed
      - python -m bikeshed update
      - bash build.sh
      - git diff
    when:
      event: ["push", "pull_request"]

  deploy:
    image: archlinux
    commands:
      - pacman -Sy
      - pacman -S git python-pip python-setuptools zola --noconfirm
      - pip install bikeshed
      - python -m bikeshed update
      - bash build.sh
      - bash deploy.sh
    secrets: ["bot_token"]
    when:
      event: ["push", "tag"]
      branch: ${CI_REPO_DEFAULT_BRANCH}
